### ISSUE TITLE
Deployment works, but no webserver.

### ISSUE THREAD

**Issue by tschettervictor** [AppJail-makejails/nextcloud#1]
A couple questions here.

Where does the .env file go? In PWD?
Deplyments runs fine with the “php” tag, but no webserver seems to be installed.

**Comment by DtxdF** [comment]
> Where does the .env file go? In PWD?

The `.env` file is used by Director and yes, it must be in the same directory as your Director file.

> Deplyments runs fine with the “php” tag, but no webserver seems to be installed.

The `*-php` images do not install any web server, that is why you see in the README that it is combined with NGINX. If you want Nextcloud with a web server, use the other tags that come with apache.

**Comment by tschettervictor** [comment]
Can I use a .env file with a "makejail" command or does it need director?

**Comment by DtxdF** [comment]
A `.env` file is used only by Director.

**Comment by tschettervictor** [comment]
> A `.env` file is used only by Director.

So running the “makejail” command would require using “-V VAR=value”?

**Comment by DtxdF** [comment]
Yes.

**Comment by DtxdF** [comment]
But don't think that putting the environment variables in `.env` is passed to the Makejail. Director will (internally) build a command that uses the `-V` arguments, so you still need to specify it in your Director file. The reason for using the `.env` file is to place things that need to be changed in your Director file and is not limited to the Makejail.

**Comment by tschettervictor** [comment]
One more thing before I close out this issue. 
Is it feasible to add the nginx and Apache config files (the files that serve the site) into one of the makejail repos? Or should the user be responsible for creating and copying their own files as it currently stands?

I’d love to add a caddy makejail to plug into Appjail, but it would require users to either
a. Create their own config file
b. Add the file into each makejail (for each server have its own file in caddy.makejail/apache.makejail etc…)
c. Add the file to the readme as it currently stands

Thanks

**Comment by DtxdF** [comment]
There is no need to add Caddy to this Makejail if Caddy can communicate with php-fpm as NGINX does. Just create a new Makejail repository (AppJail-makejails/caddy).

This is the reason for the existence of the `*-php` images, to use any web server only if it can communicate with php-fpm. The `*-apache` images are only for fast deployment of services. Caddy should be used as a reverse proxy like NGINX.

**Comment by DtxdF** [comment]
And don't worry if the user needs to copy a file. In fact, AppJail takes care of this task. The user only writes their configs once and in most cases doesn't need to rewrite them. AppJail automates a lot of things, but a config like nginx or maybe caddy is one thing the user wants to be fine tuned to their environment.

**Comment by tschettervictor** [comment]
Indeed it can! 

From the deployment page I can see you are mounting the root directory into both the nextcloud and nginx jails. Clever!

I’ll see what I can do with caddy.

**Comment by DtxdF** [comment]
> I’ll see what I can do with caddy.

Thank you in advance for your contribution.
